"""
septum.py -- the medial-septum pacemaker the whole arc kept demanding.

Across v16-v18 the resonator neuron's own results kept pointing at one missing
piece: a CLOCK. v16 found latency = logic depth ("the structural reason a real
brain needs a clock"). v17 found carry latency linear in word width. v18's
continuous field DEMANDED a capture latch. Every one of those is a statement
about timing -- about needing something to say "now settle, now advance, now
hold." In the brain, that something is the theta rhythm, generated by the
medial septum and paced onto the hippocampus.

This file builds that pacemaker, using the exact mechanism from Vardalakis et
al. 2024 (eLife, "A dynamical computational model of theta generation in
hippocampal circuits"): the medial septum as a bank of coupled Kuramoto phase
oscillators with a phase-reset term.

  Each oscillator i:
     dtheta_i/dt = omega_i + (k/N) sum_j sin(theta_j - theta_i)
                            + G_reset * X(t) * Z(theta_i)
  where
     omega_i  ~ Normal(2*pi*f0, sigma)      natural theta frequencies
     k        coupling (synchronization) strength
     X(t)     external reset input (downstream firing fed back -- the loop)
     Z(theta) phase response curve: how a reset pulse shifts the phase,
              depending on WHEN in the cycle it lands

  The ensemble theta is read from the complex order parameter
     r(t) = (1/N) sum_j exp(i theta_j) = A(t) exp(i phi(t))
  and the output rhythm is a rectified cosine of the mean phase phi, scaled by
  the coherence A -- exactly Vardalakis's I_theta(t).

WHY THIS IS THE RIGHT PACEMAKER FOR THIS PROJECT (not a generic clock):
  - It is a POPULATION of coupled oscillators averaged into one rhythm -- the
    same form as the Homeostatic Coupler at edge-of-chaos that produced the
    ORIGINAL ACCIDENT. A bank of edge-poised oscillators, tipped into a shared
    rhythm.
  - It PHASE-RESETS on an input. v18's PerceptionLab graph already wired the
    coupler's regime into the neuron's reset ports; this is what that wire is
    FOR, characterized: a salient input re-aligns the clock to a defined phase.
  - The reset input is DOWNSTREAM firing fed back to the pacemaker -- the same
    feedback loop shape as the accident (splitter taps -> coupler).

PerceptionLab / Antti Luode, with Claude. Helsinki, June 2026.
Do not hype. Do not lie. Just show.
"""
import numpy as np


def prc_Z(theta):
    """Phase response curve Z(theta): how strongly, and in which direction, a
    reset input shifts an oscillator's phase as a function of its current
    phase. Vardalakis use a PRC inspired by hippocampal pyramidal-cell PRCs
    (Lengyel 2005, Akam 2012): predominantly phase-ADVANCING, vanishing near
    the peak. A simple, faithful form is Z(theta) = -sin(theta): zero at the
    peak (theta=0), maximal mid-cycle, sign set so an input pulls the phase
    toward the peak (the reset target). This is the standard sinusoidal PRC of
    a system relaxing toward its cycle peak."""
    return -np.sin(theta)


class KuramotoSeptum:
    """The medial septum as a bank of Kuramoto oscillators producing a
    dynamical theta rhythm with phase reset. Vardalakis et al. 2024."""

    def __init__(self, n=50, f0=7.0, sigma=0.5, k=6.0, g_reset=25.0,
                 g_theta=1.0, dt=1e-3, seed=0):
        rng = np.random.default_rng(seed)
        self.n = int(n)
        self.dt = float(dt)                 # seconds per step (1 ms)
        self.f0 = float(f0)                 # center theta frequency (Hz)
        # natural angular frequencies, normal around 2*pi*f0
        self.omega = 2 * np.pi * rng.normal(f0, sigma, self.n)
        self.k = float(k)                   # coupling strength
        self.g_reset = float(g_reset)       # reset input gain
        self.g_theta = float(g_theta)       # output theta gain
        self.theta = rng.uniform(0, 2 * np.pi, self.n)  # initial phases
        self.A = 0.0                        # order-parameter amplitude (coherence)
        self.phi = 0.0                      # ensemble mean phase
        self.I_theta = 0.0                  # output theta drive (rectified cos)

    def order_parameter(self):
        r = np.mean(np.exp(1j * self.theta))
        return abs(r), np.angle(r)

    def step(self, reset_input=0.0):
        """Advance one dt. reset_input = X(t), the downstream firing fed back
        to the septum (0 if none). Returns the output theta drive I_theta."""
        A, phi = self.order_parameter()
        self.A, self.phi = A, phi
        # mean-field Kuramoto coupling: (k/N) sum_j sin(theta_j - theta_i)
        # = k * A * sin(phi - theta_i)   (exact mean-field identity)
        coupling = self.k * A * np.sin(phi - self.theta)
        reset = self.g_reset * float(reset_input) * prc_Z(self.theta)
        dtheta = self.omega + coupling + reset
        self.theta = (self.theta + self.dt * dtheta) % (2 * np.pi)
        # output theta: rectified cosine of the mean phase, scaled by coherence
        A2, phi2 = self.order_parameter()
        self.I_theta = self.g_theta * A2 * max(np.cos(phi2), 0.0)
        return self.I_theta

    # convenience reads
    def theta_phase(self):
        return self.phi

    def coherence(self):
        return self.A


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import numpy as np

    print("=" * 70)
    print("KURAMOTO SEPTUM -- does the oscillator bank generate a theta rhythm?")
    print("=" * 70)
    sep = KuramotoSeptum(n=50, f0=7.0, k=6.0, dt=1e-3, seed=1)
    fs = 1000.0  # 1 kHz (dt=1ms)
    T = 2.0
    out = np.array([sep.step(0.0) for _ in range(int(T * fs))])

    # dominant frequency of the generated rhythm
    sig = out - out.mean()
    freqs = np.fft.rfftfreq(len(sig), 1 / fs)
    P = np.abs(np.fft.rfft(sig)) ** 2
    f_peak = freqs[1 + np.argmax(P[1:])]
    print(f"  generated rhythm peak frequency: {f_peak:.2f} Hz "
          f"(target theta f0 = 7 Hz)")
    print(f"  final coherence (order parameter A): {sep.coherence():.3f} "
          f"(0=incoherent, 1=fully synchronized)")
    print(f"  -> {'PASS: theta-band rhythm self-organizes' if 4 <= f_peak <= 12 else 'FAIL'}")

    print("\n" + "=" * 70)
    print("PHASE RESET -- does a pulse re-align the clock to a defined phase?")
    print("=" * 70)
    sep = KuramotoSeptum(n=50, f0=7.0, k=6.0, dt=1e-3, seed=2)
    # run two identical septa; pulse one mid-run, compare phases after
    sep2 = KuramotoSeptum(n=50, f0=7.0, k=6.0, dt=1e-3, seed=2)
    phases_unpulsed = []
    phases_pulsed = []
    for t in range(1000):
        sep.step(0.0)
        # deliver a strong reset pulse to sep2 at t=500 for 5 ms
        rin = 1.0 if 500 <= t < 505 else 0.0
        sep2.step(rin)
        phases_unpulsed.append(sep.theta_phase())
        phases_pulsed.append(sep2.theta_phase())
    # phase difference well after the pulse
    dphi = np.angle(np.exp(1j * (np.array(phases_pulsed[-200:]) -
                                 np.array(phases_unpulsed[-200:]))))
    print(f"  mean phase shift induced by the pulse: {np.mean(dphi):+.3f} rad "
          f"({np.degrees(np.mean(dphi)):+.0f} deg)")
    print(f"  -> {'PASS: the pulse measurably reset the theta phase' if abs(np.mean(dphi)) > 0.05 else 'no reset detected'}")
    print("\nThe septum self-organizes a theta rhythm from a bank of edge-poised")
    print("oscillators, and a salient input resets its phase -- exactly the")
    print("pacemaker the resonator neuron's latency findings kept demanding.")
