"""Visualize the theta-paced adder: the generated theta rhythm with stage
advances (carry hops) marked on the theta peaks. Shows the computation riding
the self-organized clock."""
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from septum_paced_adder import theta_paced_add
from septum import KuramotoSeptum

# run a multi-bit add and capture the theta trace + stage times
got, theta, times = theta_paced_add(7, 1, 4)   # 7+1=8: carry ripples all bits

fs = 1000.0
t = np.arange(len(theta)) / fs

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 6), sharex=True,
                                gridspec_kw={'height_ratios':[2,1]})

# top: the generated theta rhythm
ax1.plot(t, theta, color='#7a4fb5', lw=1.2, label='generated theta I_theta(t)')
ax1.fill_between(t, 0, theta, color='#7a4fb5', alpha=0.2)
for i, st in enumerate(times):
    ax1.axvline(st, color='#d4663b', ls='--', lw=1.2, alpha=0.8)
    ax1.text(st, ax1.get_ylim()[1]*0.92, f'bit {i}\ncarry hop',
             color='#d4663b', fontsize=7, ha='center', va='top')
ax1.set_ylabel('theta drive')
ax1.set_title(f'Septum-paced ripple adder: 7 + 1 = {got}  '
              f'(carry ripples one theta cycle at a time)\n'
              f'the clock is GENERATED by a Kuramoto septum, not imposed by a scheduler',
              fontsize=10)
ax1.legend(loc='upper right', fontsize=8)

# bottom: coherence over time (the order parameter), showing the loop is live
sep = KuramotoSeptum(n=50, f0=7.0, k=6.0, dt=1e-3, seed=0)
coh = []
for _ in range(300): sep.step(0.0)
reset_in = 0.0
last_phase = None; stage = 0
for i in range(len(theta)):
    sep.step(reset_in); reset_in = 0.0
    ph = sep.theta_phase()
    coh.append(sep.coherence())
    if last_phase is not None and last_phase > 2.5 and ph < 0.5 and stage < 4:
        reset_in = 1.0; stage += 1
    last_phase = ph
ax2.plot(t, coh, color='#3b7dd4', lw=1.0)
ax2.set_ylabel('coherence A')
ax2.set_xlabel('time (s)')
ax2.set_ylim(0, 1)
ax2.text(0.02, 0.85, 'order parameter A (ensemble synchrony) -- dips at each '
         'feedback reset, the loop is live',
         transform=ax2.transAxes, fontsize=7, color='#3b7dd4')

fig.tight_layout()
fig.savefig("septum_paced.png", dpi=120, bbox_inches='tight')
print(f"saved septum_paced.png   (7+1={got}, {len(times)} carry hops on generated theta)")
